### ISSUE TITLE
Flower doesn't show on avatar

### ISSUE THREAD

**Issue by UnexpectedMushroom** [HabitRPG/habitica-chat-extension#12]
Not a huge deal, but it'd be nice ^^

**Comment by crookedneighbor** [comment]
👍 I've advertised this in the aspiring coders guild.

**Comment by UnexpectedMushroom** [comment]
Yay ^^ Thank you~

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
