### ISSUE TITLE
NPC Colours are showing as Dark Blue instead of Black

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica-chat-extension#16]
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 8.1 32-bit

## Description

@Its Bailey is showing as Dark Blue instead of black as shown in image.

![chatnpcwrongcolour](https://cloud.githubusercontent.com/assets/14116069/16772087/2144eade-4896-11e6-9b50-170dfdcc6d8e.png)

**Comment by crookedneighbor** [comment]
Duplicate of https://github.com/HabitRPG/habitica-chat-extension/issues/3

**Comment by cTheDragons** [comment]
ok I did check for that issue... must be the late night crazies are hiding me on this. Sorry for the extra effort.

**Comment by crookedneighbor** [comment]
No worries.
