### ISSUE TITLE
Scroll-wheel events passed to window behind when scrolling stops

### ISSUE THREAD

**Issue by synrg** [HabitRPG/habitica-chat-extension#19]
This is a fairly minor issue, but when I scroll-wheel down to the bottom of a chat window's messages, once I have reached the bottom, scroll events start being passed through to the page behind it, causing it to scroll. Certainly not what I expected, which is that scrolling should've stopped when I reached the bottom.

Similarly, if I'm in the Send window composing a multi-line response and the scroll-bar appears, so long as there are lines above or below to scroll, the scroll-wheel will scroll the response, but as soon as it hits the top or bottom, scroll-wheel events pass to the window behind.

Thanks,
Ben

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
