### ISSUE TITLE
@mention Suggestions

### ISSUE THREAD

**Issue by iptohip777** [HabitRPG/habitica-chat-extension#21]
Hello,

When I hit @, I usually get a dropdown list of people within the group/party that I can choose to @mention. For ex: 
![image](https://cloud.githubusercontent.com/assets/23444069/21533702/5992c054-cd12-11e6-8661-0a427d63b6f8.png)

Could that feature also be available within the chat windows provided by the extension?

**Comment by crookedneighbor** [comment]
This is a good feature request, but it'll be a while till I get around to implementing it. There's some larger architectural changes I want to make, which will need to be done before this is implemented.

**Comment by iptohip777** [comment]
Got it. Thanks!
 





On Fri, Dec 30, 2016 11:59 AM, Blade Barringer notifications@github.com
wrote:
This is a good feature request, but it'll be a while till I get around to
implementing it. There's some larger architectural changes I want to make, which
will need to be done before this is implemented.

**Comment by cTheDragons** [comment]
Hi @iptohip777 

Not sure you already know, while your waiting for this feature you can click on the person name from the chat and it will appear in the chat talk box.

Thanks

**Comment by coder-extreme** [comment]
I fixed the feature @cTheDragons mentioned with Pull Request #35.

**Comment by Alys** [comment]
I'm closing this because I believe it was fixed in https://github.com/HabitRPG/habitica-chat-extension/pull/37 (as documented in https://github.com/HabitRPG/habitica-chat-extension/pull/35) however this can be reopened if I'm wrong.
