### ISSUE TITLE
"Click here to link to your account" has no effect

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-chat-extension#25]
I installed from the Chrome extensions shop yesterday onto Chrome Version 56.0.2924.87. The extension installed cleanly, but when I click the link "Click here to link to your account," it opens the Habitica API Settings page and has no further effect.

This has persisted through refreshes of the Habitica site and browser restarts.

**Comment by crookedneighbor** [comment]
This is because we added the loading screen, which throws everything off. Haven't had a chance to fix it.

**Comment by crookedneighbor** [comment]
Just published this. Should work now.
