### ISSUE TITLE
GitHub link and Manual Setup link overlap, making Manual Setup inaccessible

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-chat-extension#26]
When I click the Habitica Chat Extension icon in Chrome Version 56.0.2924.87, it looks like this:

![image](https://cloud.githubusercontent.com/assets/4501321/24561843/f5fd7ecc-160d-11e7-9617-28f510e347b2.png)

It looks like there's a "Manual Setup" option at the bottom that would let me work around #25, but because the GitHub link sits on top of it, clicking it takes me to GitHub instead.

**Comment by crookedneighbor** [comment]
@SabreCat what version of the extension do you have? This PR should have fixed it: https://github.com/HabitRPG/habitica-chat-extension/pull/24

**Comment by SabreCat** [comment]
@crookedneighbor Looks like 1.4.3. I'll see if I can get it to update to 1.4.4 and recheck!

**Comment by SabreCat** [comment]
The version of the extension on the Play Store is 1.4.3. I'll check once 1.4.4 is available!

**Comment by crookedneighbor** [comment]
It should be available. Hmm... let me see about re-publishing it.

**Comment by crookedneighbor** [comment]
I must have forgotten to hit the publish button.

**Comment by Ieahleen** [comment]
It's still not resolved! And I have 1.4.4
![habitica chat client chrome web store](https://cloud.githubusercontent.com/assets/26656284/24566134/909a3af2-1658-11e7-9afa-fcc3ca434c02.png)

**Comment by crookedneighbor** [comment]
Can you take a screenshot of the app version on the chrome extensions page?

I _just_ released 1.4.4 ,so it's possible that you downloaded it while it was 1.4.3 and it hasn't yet updated automatically to 1.4.4

**Comment by SabreCat** [comment]
Mine automatically updated and this issue is now resolved for me, at least!
