### ISSUE TITLE
Swear-Word Block Message Doesn't Display

### ISSUE THREAD

**Issue by tricksyfox** [HabitRPG/habitica-chat-extension#29]
Sorry if this is the wrong place to put this!

With the implementation of the new swear-word blocker, messages containing a banned word posted to the Tavern will be blocked from posting, and a pop-up will inform the user as to why it's blocked.

Messages posted to the Tavern through the chat extension are successfully blocked, but it triggers no pop-up.

**Comment by Alys** [comment]
In addition to displaying the block warning (in whatever way; doesn't have to be a popup), the message that the user has typed should be left in the text entry field so that the user can edit it rather than having to retype from scratch.

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
