### ISSUE TITLE
NPC Contributor tier error

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica-chat-extension#3]
Originally reported https://github.com/Horacious/HabitRPG-Chat-Extension/issues/34 by @Mihakuu

Literally the only person this effects 
the npc tier is not showing right, rather showing dark blue of moderator

Not something hugely important but I wanted to point it out

Edit: Also, I've been told that they can't click my name to autofill in a reply.

**Comment by MathWhiz** [comment]
@crookedneighbor I can do it on the extension...

**Comment by cTheDragons** [comment]
ok I did check for that issue... must be the late night crazies are hiding me on this. Sorry for the extra effort.

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
