### ISSUE TITLE
random messages are highlighted not those in which one is tagged

### ISSUE THREAD

**Issue by Ieahleen** [HabitRPG/habitica-chat-extension#30]
random messages are highlighted not those in which one is tagged

two images as example below. To be clear some messages in which I am mentioned are highlighted, but it seems part of the randomness.

![immagine2](https://user-images.githubusercontent.com/26656284/30800545-a288150e-a1e0-11e7-8a10-e0e27602aa13.png)
![immagine](https://user-images.githubusercontent.com/26656284/30800549-a4dcb738-a1e0-11e7-9c81-e9d318c6f859.png)

**Comment by crookedneighbor** [comment]
Thanks for the report. I'll be doing some upgrades on Friday after the redesign launches, and this will likely be one of the things that gets taken care of.

**Comment by cTheDragons** [comment]
The highlighting is to do with how liked the message is. The higher the like count the more brighter the boarder.

It not related to tagging the user.

**Comment by Ieahleen** [comment]
I may have missed that information somewhere or never identified the other
way in which a message that @mentions is evidentiated

**Comment by cTheDragons** [comment]
Agreed it needs to be added to the wiki.
