### ISSUE TITLE
Clicking on guild names bring to old urls.

### ISSUE THREAD

**Issue by Ieahleen** [HabitRPG/habitica-chat-extension#32]
Example, the Book Lust guld has now url `https://habitica.com/groups/guild/16b96e1b-0b59-4b49-b9a7-05f20ff760e6`, but clicking on the guild name in the extension chat add simply `#/options/groups/guilds/16b96e1b-0b59-4b49-b9a7-05f20ff760e6` at the end of current url, and so don't work.

**Comment by crookedneighbor** [comment]
Thanks, just published v1.4.7 with a fix for this. Should be updated in the next hour.
