### ISSUE TITLE
Chat extension not working: Does not save API token after reload.

### ISSUE THREAD

**Issue by Lalaitha** [HabitRPG/habitica-chat-extension#33]
Hey,

For a few days I have been having issues with the extension not working. Today in the Tavern, someone else mentioned they had issues as well.

So I investigated it a bit. Turns out that when I select manual setup, my user ID is shown in both the User ID slot and the API key slot. I therefore tried changing it to the API token and reloaded. Then came the pop-up, saying that it was now linked (and the chat module shows up). But.. When I press OK for that pop-up, the website reloads and the whole issue repeats. User ID shown in both User ID and API key slot. I tried a few times, to be sure. Same issue each time. 

"Click here to link your account" is not working either (I assume it's the same issue). I'm not sure if it has something to do with the fact that the API token is now "hidden" on the website, and that the extension therefore can't locate it? Just guesses. 

For reference, I'm using Google Chrome, version 61.0.3163.100 (Officiel version) (64-bit).

**Comment by crookedneighbor** [comment]
This is definitely because of the change to how the api token is stored on the site. Will look into fixing this soon (today, hopefully).

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitica-chat-extension/commit/a4010b420259584c49f6a63437a30c391142bfcb

I've published a new version. Should be available automatically in about an hour.
