### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Mikaela** [HabitRPG/habitica-chat-extension#34]
I think that the Habitica inbuild chat is somewhat bad and I would hope thie extension to help me use it, but I use Firefox and it's only for Chrome.

However Firefox 57 only supports WebExtensions and I have understood them to be easy to port across web browsers and I hope that porting this one would be doable and not too much effort or out-of-scope.

* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by crookedneighbor** [comment]
Want to open a PR and give it a try? :)

**Comment by Mikaela** [comment]
I am not a coder, sorry :(

**Comment by crookedneighbor** [comment]
To be honest, this isn't high on the roadmap of priorities for this repo, but I can see if I can fit it in eventually. Hoping to get a broader redesign done soon.

**Comment by crookedneighbor** [comment]
If someone else wants to take a stab at it, and it's not too complicated to do, they should go for it.

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
