### ISSUE TITLE
https://habitica.com/apidoc/ Just continually loads

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica-chat-extension#36]
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description

When going to the URL Address https://habitica.com/apidoc/ I just get a continuous loading screen, that is it never shows itself.

(I have tried multiple times and the last attempt I waited over an hour for any results).

![apijustloads](https://cloud.githubusercontent.com/assets/14116069/15561210/a69f16bc-2336-11e6-8067-d2b874fbc7e6.png)

**Comment by Alys** [comment]
It looks like the transfer wasn't successful earlier and it closed the issue instead. It's a beta feature so `shrug`. I've tried the transfer again now and reopened the issue - seems to have worked!

**Comment by cTheDragons** [comment]
This can be closed now as it has been fixed with Pull Request #37.
