### ISSUE TITLE
Extension making lots of unauthenticated requests

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica-chat-extension#38]
We had to disable the AJAX calls the extension was making because from our logs it looked like it continuously made a lot of unauthenticated requests to the api (no user id or api key)

**Comment by Alys** [comment]
@paglias would it be possible to include an example of the log file message here? I'd add it myself but I don't know how to identify which records in Loggly are from the extension and which aren't.

If you prefer, send me just the link to one example and I'll copy the record here with neat formatting and with redaction of any details that might identify a person's private information (IP addresses, etc).

**Comment by paglias** [comment]
It's the `Missing authentication headers` error message that can happen from any route when the `x-api-user` and `x-api-key` headers are empty.

<img width="801" alt="Schermata 2019-03-09 alle 11 34 28" src="https://user-images.githubusercontent.com/589911/54070372-5496b500-425f-11e9-90fe-d131f4381516.png">

**Comment by cTheDragons** [comment]
@paglias Does this only occur on the /api/v3/user call? or other calls?

**Comment by paglias** [comment]
Unfortunately it's difficult to distinguish between requests made by the
extension and other ones, we just know that after the update was released
these errors skyrocketed and then went back to normal levels after the Ajax
calls were disabled

The majority are for sure calls to /api/v3/user but there could be other
routes as well

Il Sab 9 Mar 2019, 14:37 cTheDragons <notifications@github.com> ha scritto:

**Comment by cTheDragons** [comment]
Is there anyway for us to see these errors from the client side, without access to the server logs?

**Comment by paglias** [comment]
You should be able to see all the requests made by the extension from the
network tab in the developer tools in Chrome (of the extension itself not
of habitica.com)

Il Sab 9 Mar 2019, 20:30 cTheDragons <notifications@github.com> ha scritto:

**Comment by cTheDragons** [comment]
Thanks. Will check it out.

The bad requests are occurring because the system is try to query when the User ID/API Token is blank or incorrect. 

After my quick check of the code, it appears it does not complete a check that the User ID/API Token is valid on loading and tries to complete everything regardless of the error messages.

**Comment by cTheDragons** [comment]
After some more quick investigation it looks like the server issues are likely to this interval code at [Line 795](https://github.com/HabitRPG/habitica-chat-extension/blob/master/chrome/mainChat/chat_inPage.js#L795) 

It is checking every 20 seconds regardless if the chat is paused or not to update the notifications in the guild list.

From what I can gather, what needs to change is
+ Only complete the ajax call if globalNotifications is actually true (set)
+ Stop if the chat is idle.
+ Possible increase the refresh rate so it does not overload the servers.

Thoughts?

**Comment by paglias** [comment]
That looks good, but I think the problem is also that people who didn't link the extension to their account still had requests being sent so I guess we need to check that the api keys are actually set

**Comment by cTheDragons** [comment]
Agreed. Though I think it only limited to two bad requests if the name is not set correctly.
