### ISSUE TITLE
Minified code preventing publication on Firefox Add-ons

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica-chat-extension#40]
We got an email from the Firefox Add-ons website (https://addons.mozilla.org/it/firefox/) letting us know that the extension can't be published as long as it contains minified code 

> This version contains obfuscated, minified, concatenated or otherwise machine-generated code. Please provide the original sources, together with instructions on how to generate the final XPI. Source code must be provided as an archive and uploaded using the source code upload field, which can be done during submission or on the version page in the developer hub

I think the issue comes from the presence of minified jquery code [here](https://github.com/HabitRPG/habitica-chat-extension/blob/master/firefox/mainChat/chat.js#L2-L5), [here](https://github.com/HabitRPG/habitica-chat-extension/blob/master/firefox/mainChat/chat_inPage.js#L1-L4) and the markdown code [here](https://github.com/HabitRPG/habitica-chat-extension/blob/master/firefox/resources/habitica-markdown.min.js).

It'll have to be moved to separate files (jquery) and unminified before it can be published

cc @cTheDragons

**Comment by crookedneighbor** [comment]
Alternatively, jquery can just be removed as a dependency. :)

**Comment by crookedneighbor** [comment]
I think I’ll have a bit of free time tonight or tomorrow. Will give it a go if I have the chance.

**Comment by cTheDragons** [comment]
Hi @crookedneighbor  Any luck?

**Comment by crookedneighbor** [comment]
Yeah, it’s in progress.

**Comment by crookedneighbor** [comment]
Turns out there’s a ton of jquery in these files :dizzy:

**Comment by crookedneighbor** [comment]
Got it started here: https://github.com/crookedneighbor/habitica-chat-extension/tree/remove_jquery

**Comment by crookedneighbor** [comment]
Not gonna have a chance to keep working on it for a while, so if y'all want to go that route, feel free to use the branch and go from there.

TBH, if you want a quick fix, just use the un-minified versions of the scripts.

**Comment by cTheDragons** [comment]
I'm thinking we should use that. As that all I would do.

@paglias Did you have any thoughts?

**Comment by paglias** [comment]
I'm fine with just using the unminified version !

Il Ven 3 Mag 2019, 11:02 cTheDragons <notifications@github.com> ha scritto:

**Comment by cTheDragons** [comment]
@crookedneighbor are you ok created the Pull request or would you like me to do it?

Do we need to do any formal testing with it?

**Comment by paglias** [comment]
@cTheDragons I'd say if it loads and works normally for us we're good to go without extensive testing

**Comment by godless-toast** [comment]
What's the status? I know there's work being done to make the developer's lives easier with #42, but it's been almost 2 months and I'd love to be able to use the extension on Firefox.

**Comment by benjaminbhollon** [comment]
I think we're trying to work out bugs in Browserify right now.

**Comment by paglias** [comment]
Published again, let's see how it goes

**Comment by paglias** [comment]
It's been approved 🎉 thanks @benjaminbhollon !

**Comment by Alys** [comment]
For the benefit of anyone following this issue, it looks like its been moved to a new URL: https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-2/  (or possibly the link in the wiki page had been wrong).

I've updated the wiki page (https://habitica.fandom.com/wiki/Chat_Extension).
