### ISSUE TITLE
Changing settings doesn't seem to affect the extension

### ISSUE THREAD

**Issue by benjaminbhollon** [HabitRPG/habitica-chat-extension#56]
So, since I started work back up on the Chat Extension, I've noticed that changing the settings doesn't seem to be affecting the extension at all. It just keeps using the default settings.

I'm not quite sure why this is yet, but I'll be working on it. I would appreciate any insights people have as to why this might be happening.

**Comment by junewerner** [comment]
This may be resolved in pull #61. I ran into chrome not saving settings when working on adding the option to hide system messages. Not sure if it's the same issue that you were seeing.
