### ISSUE TITLE
No Avatars

### ISSUE THREAD

**Issue by junewerner** [HabitRPG/habitica-chat-extension#60]
Even when "Disable Avatars for Faster Load" is unchecked, avatars don't appear for both me and other people. Tested in chrome and in firefox. 

![noAvatar](https://user-images.githubusercontent.com/46098097/83066877-577bf200-a02b-11ea-9a06-23e13786687c.png)

**Comment by junewerner** [comment]
The looks to be the same as issue #43, where the "data-v" value needed to be updated. Looks like it needs to be updated to "data-v-b43ab9da" now. I can handle this fix. Just curious though, does anyone know what the data-v value does?

**Comment by benjaminbhollon** [comment]
Oh, I built a fix for this and never uploaded because I was going to add other features to the same pull request and never got around to it. I'll go take a look again and upload some time over the weekend. I can't remember what the data-v thing does, but it's some sort of auto-generated thing

**Comment by juanj** [comment]
@benjaminbhollon ping. Would be great if you can have a look here.
If you are too busy I can take over this issue and, if is ok for you, use the code you had written for this.

On a side note, it's usually a best practice to focus pull request on only one feature at a time and keep it small when possible. This way it is easier to discuss, faster to review and if merge conflicts arrive is probably easy to solve.
To do this the usual procedure is to make a different branch for each feature/pull request.

**Comment by benjaminbhollon** [comment]
Oh, yeah, sorry. I've been taking a step back from coding due to a lot of things going on at my end. Sorry for not giving you a heads up.

The idea behind fixing this bug would be to read the data-v- attribute name from one of the avatars on the page when the site is loaded and use it when generating the avatars. You should be able to do this fairly easy with jQuery.

Again, sorry for not telling y'all.

**Comment by juanj** [comment]
No worries! I hope everything is fine
