### ISSUE TITLE
Use the same code base for multiple browsers

### ISSUE THREAD

**Issue by juanj** [HabitRPG/habitica-chat-extension#68]
Right now the add-on uses two copies of the same code to support multiple browser (Chrome and Firefox). This feels really ineficient. Double the work for each feature/bug fix.

There must be a better way to handle this. I don't have much experience building browser add-ons but this is worth investigating.
Maybe share the same core JavaScript files and use different sets of Manifest/Platform dependent files when "compiling" the extension.

This may also open the door to support more browsers easily.

**Comment by cTheDragons** [comment]
Wit the binary files, maybe it best we use Git LFS?

**Comment by cTheDragons** [comment]
We looked in using Browserfy. However for those of coding on a non-Linux platform, (ie windows) we were unable to get it working.
