### ISSUE TITLE
Automatically grab api token

### ISSUE THREAD

**Issue by juanj** [HabitRPG/habitica-chat-extension#72]
Currently, you need to manually input your user id and API token or go to the API settings page for the extension to grab them.
After looking at the code, I found that the user id and API token are stored on the `localStorage` and can be accessed by calling `window.localStorage.getItem('habit-mobile-settings')`

Should the extension automatically grab them from the `localStorage`?
Or maybe is important for the user to manually authorize the extension?

**Comment by paglias** [comment]
I'd say it's important that the user manually authorizes the extension
