### ISSUE TITLE
Avatars not showing in Chat client since v1.4.0 Update

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica-chat-extension#8]
### General Info

- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit

### Description

Avatars are no longer showing in the chat client. Not sure if it is an extension of the extra text we can see. (Looks like all 200). 
See image below
![chatavatarnotshowing](https://cloud.githubusercontent.com/assets/14116069/15659324/313e7226-270c-11e6-8040-ce083ac9b005.png)

This is what it use to look like but the Avatars would eventually show not just not display.
![Chat With Avatars](https://cloud.githubusercontent.com/assets/14116069/15453546/2ec57fa4-205d-11e6-8fa2-5135c642eb11.png)

If it is could we have an option to turn it back on and have less text? It makes it easier for Socialite when answering questions based on how their Avatar is looking what level they are at without having to look up the stats. Also I like looking at everyone awesome costumes.

**Comment by crookedneighbor** [comment]
Sorry for the delay, looking into this now.

**Comment by crookedneighbor** [comment]
Just published a new version that should include avatars. I think it needs some visual tweaks, but the basic gist is there.

**Comment by cTheDragons** [comment]
Am I missing something? The chat client is still 1.4.0 (30 May 2016) on the Google site.

**Comment by crookedneighbor** [comment]
Hmm... I'm sure I forgot to hit a publish button or something on the google dashboard. Will re-submit today.

**Comment by crookedneighbor** [comment]
Yep. That was it. Got it all prepped and never published.
